/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
var todosId = 1;
const PORT = 3000;
const path = require("path");
const fs = require("fs");
const express = require("express");
const bodyParser = require("body-parser");
const app = express();
app.use(bodyParser.json());
const todosFilePath = path.join(__dirname, "files", "todos.json");

app.get("/todos", (req, res) => {
  fs.readFile(todosFilePath, (err, data) => {
    if (err) {
      console.log(err);
      return res.status(500).send("Error in reading file");
    }
    if (data === "") {
      data = "[]";
    }
    return res.status(200).send(JSON.parse(data));
  });
});

app.post("/todos", (req, res) => {
  const title = req.body.title;
  const completed = req.body.completed;
  const description = req.body.description;
  const todoId = todosId++;
  const todo = {
    title: title,
    completed: completed,
    description: description,
    id: todoId,
  };
  fs.readFile(todosFilePath, (err, data) => {
    if (err) {
      console.log(err);
      return res.status(500).send("Error in reading file");
    }
    let todos = JSON.parse(data);
    todos.push(todo);
    fs.writeFile(todosFilePath, JSON.stringify(todos), () => {
      if (err) {
        console.log(err);
        return res.status(500).send("Error in writing file");
      }
      console.log("File written successfully");
      return res.status(201).send({ id: todoId });
    });
  });
});

app.get("/todos/:id", (req, res) => {
  const todoId = parseInt(req.params.id);
  fs.readFile(todosFilePath, (err, data) => {
    if (err) {
      console.log(err);
      return res.status(500).send("Error in reading file");
    }
    if (data === "") {
      data = "[]";
    }
    const todos = JSON.parse(data);
    let todoInd = -1;
    for (let i = 0; i < todos.length; i++) {
      if (todoId === todos[i].id) {
        todoInd = i;
      }
    }
    if (todoInd === -1) {
      return res.status(404).send("Not Found");
    } else {
      return res.status(200).send(todos[todoInd]);
    }
  });
});

app.put("/todos/:id", (req, res) => {
  const todoId = parseInt(req.params.id);
  const title = req.body.title;
  const completed = req.body.completed;
  const description = req.body.description;
  fs.readFile(todosFilePath, (err, data) => {
    if (err) {
      console.log(err);
      return res.status(500).send("Error in reading file");
    }
    if (data === "") {
      data = "[]";
    }
    const todos = JSON.parse(data);
    let todoInd = -1;
    for (let i = 0; i < todos.length; i++) {
      if (todoId === todos[i].id) {
        todoInd = i;
      }
    }
    if (todoInd === -1) {
      return res.status(404).send("Not Found");
    } else {
      if (title !== undefined) {
        todos[todoInd].title = title;
      }
      if (completed !== undefined) {
        todos[todoInd].completed = completed;
      }
      if (description !== undefined) {
        todos[todoInd].description = description;
      }
      fs.writeFile(todosFilePath, JSON.stringify(todos), () => {
        if (err) {
          console.log(err);
          return res.status(500).send("Error in writing file");
        }
        console.log("File written successfully");
        return res.status(200).send(todos[todoInd]);
      });
    }
  });
});

app.delete("/todos/:id", (req, res) => {
  const todoId = parseInt(req.params.id);
  fs.readFile(todosFilePath, (err, data) => {
    if (err) {
      console.log(err);
      return res.status(500).send("Error in reading file");
    }
    if (data === "") {
      data = "[]";
    }
    const todos = JSON.parse(data);
    let todoInd = -1;
    for (let i = 0; i < todos.length; i++) {
      if (todoId === todos[i].id) {
        todoInd = i;
      }
    }
    if (todoInd === -1) {
      return res.status(404).send("Not Found");
    } else {
      todos.splice(todoInd, 1);
      fs.writeFile(todosFilePath, JSON.stringify(todos), () => {
        if (err) {
          console.log(err);
          return res.status(500).send("Error in writing file");
        }
        console.log("File written successfully");
        return res.status(200).send("OK");
      });
    }
  });
});

// app.listen(PORT, () => {
//   console.log(`Example app listening on port ${PORT}`);
// });

module.exports = app;
